import React, { useState } from 'react';
import { supabase } from '../../utils/supabaseClient';
import { logger } from '../../utils/logger';
import { X, Mail, Lock, Sparkles, AlertCircle, Eye, EyeOff, Info, ArrowLeft, CheckCircle, Copy, HelpCircle, Key, User } from 'lucide-react';
import { useAuthStore } from '../../store/useAuthStore';

export const TOS_PLACEHOLDER_TEXT = `WildVision Terms of Service

Last Updated: June 28, 2026

Welcome to WildVision. Please read these Terms of Service ("Terms") carefully before using our platform, website, and rendering services. By accessing or using WildVision, you agree to be bound by these Terms.

1. User Ownership (Intellectual Property)
You retain exclusive, 100% ownership of all original content you upload or create on WildVision. This includes your custom 2D JSON layouts, your structural designs, and any original photographs of your home or project space that you upload. We claim no ownership over your intellectual property.

2. AI Processing and Outputs
WildVision utilizes third-party artificial intelligence services (such as Google) to generate photorealistic 3D renders from your layouts.

  - Privacy: Your uploaded photos and layouts are processed solely for the purpose of generating your requested render.
  - Ownership of Renders: You own the final generated images. However, please note that under current intellectual property laws, purely AI-generated images may not be eligible for traditional copyright registration.
  - No Training: We do not sell your personal photos or layouts to train public AI models.

3. Limitation of Liability & Professional Advice
WildVision is a visualization tool. We do not guarantee the structural integrity, code compliance, or exact material estimations of the layouts. The generated renders and designs are for conceptual and illustrative purposes only. Always consult a licensed contractor, architect, or structural engineer before commencing any physical construction or remodeling work. You assume all risk for reliance on the outputs generated by the platform.`;

export const PRIVACY_PLACEHOLDER_TEXT = `Privacy Policy 

1. Introduction
Welcome to WildVision. We respect your privacy and are committed to protecting the personal data and intellectual property you bring into our application. This policy explains what data we collect, how we securely store it on our own infrastructure, and how we use it to provide you with our visualization tools.

2. What Data We Collect
To provide you with our application, we collect the following types of information:

    Account Data: When you create an account, we collect your First Name, Last Name, and Email Address.

    User Content: We collect the data you actively create or upload within the app, including 2D JSON structural layouts, room dimensions, custom material choices, and any project space photographs you upload for AI rendering.

    Technical & Security Data: When you access the app, we automatically collect basic technical information, including your IP address, browser type, and operating system, to ensure the security and performance of our application.

3. How We Use Your Data
We use your data strictly to operate and improve WildVision. Specifically, we use it to:

    Securely authenticate your account and save your project layouts.

    Calculate material estimations and structural boundaries.

    Generate photorealistic 3D renders based on your explicit requests.

    Monitor for malicious network activity and prevent unauthorized access.

4. How We Store and Share Your Data (Our Self-Hosted Promise)
We do not sell, rent, or trade your personal information, layouts, or photos to third-party advertisers or data brokers.

Unlike many cloud applications, your account data and user content are stored securely on our proprietary, self-hosted database infrastructure.

We only share specific, necessary data packets with essential third-party service providers to make the application function securely:

    Network Security: We route our application traffic through security and proxy providers (e.g., Cloudflare) strictly to protect against DDoS attacks and malicious traffic. This involves the temporary processing of IP addresses and browser footprints.

    AI Rendering API: When you explicitly request an AI render, the required blueprint images, uploaded photos, and text prompts are transmitted securely via API to our enterprise AI provider (Google Gemini). We restrict these providers from using your private images or layouts to train their public AI models.

5. Data Retention and Your Rights
You have complete control over your data. You may view, edit, or permanently delete your account and all associated data at any time.

    Self-Deletion: You can permanently erase your account, layouts, and renders by utilizing the "Delete Account" button located within your Account settings panel. Upon confirmation, your data is immediately purged from our active self-hosted database.

6. Changes to this Policy
We may update this policy as we add new features to WildVision. If we make significant changes, we will notify you via the email address associated with your account or through a prominent notice within the application.

7. Contact Us
If you have any questions about this Privacy Policy or how your data is handled, please contact us at: support@subfloor.app`;

interface AuthModalProps {
  isOpen: boolean;
  onClose: () => void;
  triggerMessage?: string;
  authReason?: string;
}

export const AuthModal: React.FC<AuthModalProps> = ({ 
  isOpen, 
  onClose,
  triggerMessage,
  authReason
}) => {
  const { isAuthModalOpen, authReasonMessage, closeAuthModal } = useAuthStore();
  
  // View mode: 'login', 'recovery', 'otp' or 'signup'
  const [viewMode, setViewMode] = useState<'login' | 'recovery' | 'otp' | 'signup'>('login');
  
  // Recovery mode within the recovery view: 'password' or 'username'
  const [recoveryMode, setRecoveryMode] = useState<'password' | 'username'>('password');
  
  const [email, setEmail] = useState('');
  const [recoveryEmail, setRecoveryEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  // Sign Up Mode States
  const [signUpEmail, setSignUpEmail] = useState('');
  const [signUpPassword, setSignUpPassword] = useState('');
  const [signUpConfirmPassword, setSignUpConfirmPassword] = useState('');
  const [signUpFirstName, setSignUpFirstName] = useState('');
  const [signUpLastName, setSignUpLastName] = useState('');
  const [showSignUpPassword, setShowSignUpPassword] = useState(false);
  const [showSignUpConfirmPassword, setShowSignUpConfirmPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [signUpSuccess, setSignUpSuccess] = useState(false);
  const [signUpHasAgreedToTerms, setSignUpHasAgreedToTerms] = useState(false);

  // Legal Modal States
  const [isTermsOpen, setIsTermsOpen] = useState(false);
  const [isPrivacyOpen, setIsPrivacyOpen] = useState(false);

  // Live client-side validations
  const isSignUpPasswordLengthValid = signUpPassword.length >= 6;
  const isSignUpPasswordMatching = signUpPassword === signUpConfirmPassword;
  const isSignUpEmailValid = signUpEmail.trim().length > 0 && signUpEmail.includes('@');
  const isSignUpFirstNameValid = signUpFirstName.trim().length > 0;
  const isSignUpLastNameValid = signUpLastName.trim().length > 0;
  const isSignUpValid = isSignUpPasswordLengthValid && 
    isSignUpPasswordMatching && 
    isSignUpEmailValid && 
    isSignUpFirstNameValid && 
    isSignUpLastNameValid && 
    signUpHasAgreedToTerms;

  // Forgot Username lookup states
  const [foundUsername, setFoundUsername] = useState<string | null>(null);
  const [notFoundStatus, setNotFoundStatus] = useState<boolean>(false);
  const [copySuccess, setCopySuccess] = useState<boolean>(false);

  // Manual OTP verification states
  const [otpEmail, setOtpEmail] = useState('');
  const [otpToken, setOtpToken] = useState('');

  const activeOpen = isOpen || isAuthModalOpen;
  const activeMessage = triggerMessage || authReason || authReasonMessage;

  if (!activeOpen) return null;

  const handleClose = () => {
    closeAuthModal();
    onClose();
    // Reset state values on modal close
    setViewMode('login');
    setRecoveryMode('password');
    setError(null);
    setSuccessMessage(null);
    setFoundUsername(null);
    setNotFoundStatus(false);
    setCopySuccess(false);
    setEmail('');
    setRecoveryEmail('');
    setPassword('');
    setShowPassword(false);
    setOtpEmail('');
    setOtpToken('');
    setSignUpEmail('');
    setSignUpPassword('');
    setSignUpConfirmPassword('');
    setSignUpFirstName('');
    setSignUpLastName('');
    setShowSignUpPassword(false);
    setShowSignUpConfirmPassword(false);
    setIsSubmitting(false);
    setSignUpSuccess(false);
    setSignUpHasAgreedToTerms(false);
    setIsTermsOpen(false);
    setIsPrivacyOpen(false);
  };

  const handleSignUpSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccessMessage(null);
    setIsSubmitting(true);

    try {
      const { data, error: signUpError } = await supabase.auth.signUp({
        email: signUpEmail,
        password: signUpPassword,
        options: {
          data: {
            first_name: signUpFirstName.trim(),
            last_name: signUpLastName.trim(),
          }
        }
      });

      if (signUpError) {
        setError(signUpError.message);
        setIsSubmitting(false);
        logger.error('Action failed', { error: signUpError.message, email: signUpEmail });
        return;
      }

      logger.info('New user signed up', { email: signUpEmail });
      setSignUpSuccess(true);
    } catch (err: any) {
      console.error('Sign up error:', err);
      setError(err?.message || 'An unexpected error occurred during sign up.');
      logger.error('Action failed', { error: err?.message || String(err), email: signUpEmail });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleVerifyOtpSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccessMessage(null);
    setLoading(true);

    const cleanToken = otpToken.replace(/\s+/g, '').trim();
    if (cleanToken.length < 6) {
      setError('Please enter a valid 6-digit recovery code.');
      setLoading(false);
      return;
    }

    try {
      const { error: otpError } = await supabase.auth.verifyOtp({
        email: otpEmail,
        token: cleanToken,
        type: 'recovery',
      });

      if (otpError) {
        setError(otpError.message || 'Invalid or expired recovery code. Please check your inbox and try again.');
      } else {
        // Success: Clear OTP inputs and close the modal
        setOtpEmail('');
        setOtpToken('');
        handleClose();
      }
    } catch (err: any) {
      setError(err?.message || 'An unexpected error occurred during OTP verification.');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    try {
      const { error: signInError } = await supabase.auth.signInWithPassword({
        email,
        password,
      });
      if (signInError) {
        setError(signInError.message);
        logger.error('Action failed', { error: signInError.message, email });
      } else {
        logger.info('User logged in', { email });
        handleClose();
      }
    } catch (err: any) {
      setError(err?.message || 'An unexpected error occurred. Please try again.');
      logger.error('Action failed', { error: err?.message || String(err), email });
    } finally {
      setLoading(false);
    }
  };

  const handleRecoverySubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccessMessage(null);
    setFoundUsername(null);
    setNotFoundStatus(false);
    setLoading(true);

    try {
      if (recoveryMode === 'password') {
        const { error: recoveryError } = await supabase.auth.resetPasswordForEmail(
          recoveryEmail,
          { redirectTo: window.location.origin }
        );
        if (recoveryError) {
          setError(recoveryError.message);
        } else {
          setSuccessMessage('A password reset link has been successfully dispatched to your inbox.');
        }
      } else {
        // Forgot Username flow: query profiles table
        const { data, error: dbError } = await supabase
          .from('profiles')
          .select('username')
          .eq('email', recoveryEmail)
          .maybeSingle();

        if (dbError) {
          console.error('Database query error:', dbError);
          setError('Database query failed. Please verify your internet connection and try again.');
        } else if (data && data.username) {
          setFoundUsername(data.username);
        } else {
          // Show a generic but friendly notice stating that no matching account was disclosed 
          // to protect the security and privacy of our system and users.
          setNotFoundStatus(true);
        }
      }
    } catch (err: any) {
      setError(err?.message || 'An unexpected error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopyUsername = () => {
    if (foundUsername) {
      navigator.clipboard.writeText(foundUsername);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-900/45 backdrop-blur-xs transition-opacity duration-300"
        onClick={handleClose}
      />

      {/* Modal Container */}
      <div 
        id="auth-modal-container"
        className="relative bg-white dark:bg-slate-900 w-full max-w-md rounded-xl shadow-2xl border border-slate-200/80 dark:border-slate-800 p-6 sm:p-8 transform transition-all duration-300 overflow-hidden font-sans"
      >
        {/* Subtle decorative glow */}
        <div className="absolute top-0 right-0 -mr-16 -mt-16 w-32 h-32 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 -ml-16 -mb-16 w-32 h-32 bg-rose-500/5 rounded-full blur-3xl pointer-events-none" />

        {/* Close Button */}
        <button
          onClick={handleClose}
          type="button"
          className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
        >
          <X size={18} />
        </button>

        {/* Dynamic Header */}
        {!signUpSuccess && (
          <div className="text-center mb-5 min-h-[110px] flex flex-col items-center justify-center">
            {viewMode === 'login' ? (
              <div className="animate-fade-in flex flex-col items-center">
                <div className="inline-flex p-3 bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400 rounded-full mb-3">
                  <Sparkles size={24} className="animate-pulse" />
                </div>
                <h2 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight">
                  Welcome to WildVision
                </h2>
                <p className="text-sm text-slate-500 dark:text-slate-400 mt-1.5 font-medium">
                  Log in to manage your active design sessions
                </p>
              </div>
            ) : viewMode === 'signup' ? (
              <div className="animate-fade-in flex flex-col items-center">
                <div className="inline-flex p-3 bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400 rounded-full mb-3">
                  <Sparkles size={24} className="animate-pulse" />
                </div>
                <h2 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight">
                  Join WildVision
                </h2>
                <p className="text-sm text-slate-500 dark:text-slate-400 mt-1.5 font-medium">
                  Create an account to save patterns and renders
                </p>
              </div>
            ) : (
              <div className="animate-fade-in flex flex-col items-center">
                <div className="inline-flex p-3 bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400 rounded-full mb-3">
                  <HelpCircle size={24} className="animate-pulse" />
                </div>
                <h2 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight">
                  Account Recovery
                </h2>
                <p className="text-sm text-slate-500 dark:text-slate-400 mt-1.5 font-medium">
                  Recover your credentials securely and safely
                </p>
              </div>
            )}
          </div>
        )}

        {/* Form area with smooth dynamic toggle states */}
        {viewMode === 'login' && (
          <form onSubmit={handleSubmit} className="space-y-4 animate-fade-in">
            {/* Dynamic high-visibility notification banner */}
            {activeMessage && (
              <div id="auth-notification-banner" className="flex items-start gap-3 p-4 bg-indigo-50/90 dark:bg-indigo-950/40 border border-indigo-100 dark:border-indigo-900/30 rounded-xl text-indigo-900 dark:text-indigo-200 shadow-xs">
                <Info size={18} className="text-indigo-600 dark:text-indigo-400 shrink-0 mt-0.5" />
                <div className="flex-1 text-left">
                  <p className="font-bold text-indigo-950 dark:text-indigo-300 uppercase tracking-wider text-[10px] mb-0.5 font-mono">
                    Gated Access Required
                  </p>
                  <p className="font-medium text-xs leading-relaxed">
                    {activeMessage}
                  </p>
                </div>
              </div>
            )}

            {error && (
              <div className="flex gap-2.5 items-start p-3.5 bg-red-50 dark:bg-red-950/20 text-red-700 dark:text-red-400 border border-red-200 dark:border-red-900/30 rounded-lg text-xs font-semibold leading-relaxed">
                <AlertCircle size={16} className="shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}

            {/* Email input */}
            <div className="space-y-1">
              <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                Email Address
              </label>
              <div className="relative">
                <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                  <Mail size={16} />
                </span>
                <input
                  type="email"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="you@example.com"
                  className="w-full bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm border border-slate-200 dark:border-slate-800 rounded-lg pl-10 pr-4 py-2.5 outline-none focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900 transition font-medium"
                />
              </div>
            </div>

            {/* Password input */}
            <div className="space-y-1">
              <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                Password
              </label>
              <div className="relative">
                <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                  <Lock size={16} />
                </span>
                <input
                  type={showPassword ? 'text' : 'password'}
                  required
                  minLength={6}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  className="w-full bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm border border-slate-200 dark:border-slate-800 rounded-lg pl-10 pr-10 py-2.5 outline-none focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900 transition font-medium"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute inset-y-0 right-3 flex items-center text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"
                >
                  {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              </div>
            </div>

            {/* Styled interactive link for recovery & registration */}
            <div className="flex items-center justify-between pt-1">
              <button
                type="button"
                onClick={() => {
                  setViewMode('recovery');
                  setRecoveryMode('password');
                  setError(null);
                  setSuccessMessage(null);
                  setFoundUsername(null);
                  setNotFoundStatus(false);
                }}
                className="text-xs font-bold text-indigo-650 dark:text-indigo-400 hover:text-indigo-850 dark:hover:text-indigo-300 hover:underline transition-colors focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:focus:ring-indigo-400 rounded px-1.5 py-0.5 cursor-pointer"
              >
                Forgot credentials?
              </button>

              <button
                type="button"
                onClick={() => {
                  setViewMode('signup');
                  setError(null);
                  setSuccessMessage(null);
                }}
                className="text-xs font-bold text-indigo-650 dark:text-indigo-400 hover:text-indigo-850 dark:hover:text-indigo-300 hover:underline transition-colors focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:focus:ring-indigo-400 rounded px-1.5 py-0.5 cursor-pointer"
              >
                Sign Up
              </button>
            </div>

            {/* Submit Action */}
            <button
              type="submit"
              disabled={loading}
              className="w-full flex items-center justify-center gap-2 bg-indigo-650 hover:bg-indigo-700 text-white font-bold text-sm py-3 px-4 rounded-lg shadow-md hover:shadow-lg disabled:opacity-55 disabled:cursor-not-allowed cursor-pointer transition select-none mt-2 shrink-0 h-[44px]"
            >
              {loading ? (
                <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              ) : (
                'Log In'
              )}
            </button>
          </form>
        )}

        {viewMode === 'signup' && (
          signUpSuccess ? (
            <div className="space-y-6 text-center animate-fade-in py-6">
              <div className="inline-flex p-3.5 bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 rounded-full">
                <CheckCircle size={36} className="animate-bounce" />
              </div>
              <div className="space-y-3">
                <h3 className="text-xl font-bold text-slate-900 dark:text-white tracking-tight">
                  Account Created Successfully!
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-semibold px-4">
                  Please check your inbox for a confirmation link to activate your account.
                </p>
              </div>
              
              <div className="pt-4 px-2">
                <button
                  type="button"
                  onClick={() => {
                    setViewMode('login');
                    setSignUpSuccess(false);
                    setSignUpEmail('');
                    setSignUpPassword('');
                    setSignUpConfirmPassword('');
                    setSignUpFirstName('');
                    setSignUpLastName('');
                    setError(null);
                  }}
                  className="w-full flex items-center justify-center gap-2 bg-indigo-650 hover:bg-indigo-700 text-white font-bold text-sm py-3 px-4 rounded-lg shadow-md hover:shadow-lg transition duration-200 cursor-pointer select-none"
                >
                  <ArrowLeft size={16} />
                  <span>Return to Login</span>
                </button>
              </div>
            </div>
          ) : (
            <form onSubmit={handleSignUpSubmit} className="space-y-4 animate-fade-in">
              {error && (
                <div className="flex gap-2.5 items-start p-3.5 bg-red-50 dark:bg-red-950/20 text-red-700 dark:text-red-400 border border-red-200 dark:border-red-900/30 rounded-lg text-xs font-semibold leading-relaxed">
                  <AlertCircle size={16} className="shrink-0 mt-0.5" />
                  <span>{error}</span>
                </div>
              )}

              {/* First Name & Last Name */}
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1 text-left">
                  <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                    First Name
                  </label>
                  <div className="relative">
                    <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                      <User size={16} />
                    </span>
                    <input
                      type="text"
                      required
                      disabled={isSubmitting}
                      value={signUpFirstName}
                      onChange={(e) => setSignUpFirstName(e.target.value)}
                      placeholder="John"
                      className={`w-full text-sm border rounded-lg pl-10 pr-4 py-2.5 outline-none transition font-medium ${
                        isSubmitting 
                          ? 'bg-slate-100 dark:bg-slate-900/50 text-slate-400 dark:text-slate-500 border-slate-200 dark:border-slate-800/80 cursor-not-allowed' 
                          : 'bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 border-slate-200 dark:border-slate-800 focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900'
                      }`}
                    />
                  </div>
                </div>

                <div className="space-y-1 text-left">
                  <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                    Last Name
                  </label>
                  <div className="relative">
                    <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                      <User size={16} />
                    </span>
                    <input
                      type="text"
                      required
                      disabled={isSubmitting}
                      value={signUpLastName}
                      onChange={(e) => setSignUpLastName(e.target.value)}
                      placeholder="Doe"
                      className={`w-full text-sm border rounded-lg pl-10 pr-4 py-2.5 outline-none transition font-medium ${
                        isSubmitting 
                          ? 'bg-slate-100 dark:bg-slate-900/50 text-slate-400 dark:text-slate-500 border-slate-200 dark:border-slate-800/80 cursor-not-allowed' 
                          : 'bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 border-slate-200 dark:border-slate-800 focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900'
                      }`}
                    />
                  </div>
                </div>
              </div>

              {/* Email input */}
              <div className="space-y-1 text-left">
                <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                  Email Address
                </label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                    <Mail size={16} />
                  </span>
                  <input
                    type="email"
                    required
                    disabled={isSubmitting}
                    value={signUpEmail}
                    onChange={(e) => setSignUpEmail(e.target.value)}
                    placeholder="you@example.com"
                    className={`w-full text-sm border rounded-lg pl-10 pr-4 py-2.5 outline-none transition font-medium ${
                      isSubmitting 
                        ? 'bg-slate-100 dark:bg-slate-900/50 text-slate-400 dark:text-slate-500 border-slate-200 dark:border-slate-800/80 cursor-not-allowed' 
                        : 'bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 border-slate-200 dark:border-slate-800 focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900'
                    }`}
                  />
                </div>
              </div>

              {/* Password input */}
              <div className="space-y-1">
                <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                  Password
                </label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                    <Lock size={16} />
                  </span>
                  <input
                    type={showSignUpPassword ? 'text' : 'password'}
                    required
                    disabled={isSubmitting}
                    value={signUpPassword}
                    onChange={(e) => setSignUpPassword(e.target.value)}
                    placeholder="••••••••"
                    className={`w-full text-sm border rounded-lg pl-10 pr-10 py-2.5 outline-none transition font-medium ${
                      isSubmitting
                        ? 'bg-slate-100 dark:bg-slate-900/50 text-slate-400 dark:text-slate-500 border-slate-200 dark:border-slate-800/80 cursor-not-allowed'
                        : signUpPassword && !isSignUpPasswordLengthValid
                          ? 'bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 border-red-300 focus:border-red-500 dark:border-red-900/60 dark:focus:border-red-700 focus:bg-white dark:focus:bg-slate-900'
                          : 'bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 border-slate-200 dark:border-slate-800 focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900'
                    }`}
                  />
                  <button
                    type="button"
                    disabled={isSubmitting}
                    onClick={() => setShowSignUpPassword(!showSignUpPassword)}
                    className="absolute inset-y-0 right-3 flex items-center text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 disabled:opacity-50"
                  >
                    {showSignUpPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                  </button>
                </div>
                {signUpPassword && !isSignUpPasswordLengthValid && (
                  <p className="text-[10px] text-red-500 dark:text-red-400 font-semibold flex items-center gap-1 mt-1 animate-fade-in">
                    <AlertCircle size={12} />
                    Password must be at least 6 characters long
                  </p>
                )}
              </div>

              {/* Confirm Password input */}
              <div className="space-y-1">
                <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                  Confirm Password
                </label>
                <div className="relative">
                  <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                    <Lock size={16} />
                  </span>
                  <input
                    type={showSignUpConfirmPassword ? 'text' : 'password'}
                    required
                    disabled={isSubmitting}
                    value={signUpConfirmPassword}
                    onChange={(e) => setSignUpConfirmPassword(e.target.value)}
                    placeholder="••••••••"
                    className={`w-full text-sm border rounded-lg pl-10 pr-10 py-2.5 outline-none transition font-medium ${
                      isSubmitting
                        ? 'bg-slate-100 dark:bg-slate-900/50 text-slate-400 dark:text-slate-500 border-slate-200 dark:border-slate-800/80 cursor-not-allowed'
                        : signUpConfirmPassword && !isSignUpPasswordMatching
                          ? 'bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 border-red-300 focus:border-red-500 dark:border-red-900/60 dark:focus:border-red-700 focus:bg-white dark:focus:bg-slate-900'
                          : 'bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 border-slate-200 dark:border-slate-800 focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900'
                    }`}
                  />
                  <button
                    type="button"
                    disabled={isSubmitting}
                    onClick={() => setShowSignUpConfirmPassword(!showSignUpConfirmPassword)}
                    className="absolute inset-y-0 right-3 flex items-center text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 disabled:opacity-50"
                  >
                    {showSignUpConfirmPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                  </button>
                </div>
                {signUpConfirmPassword && !isSignUpPasswordMatching && (
                  <p className="text-[10px] text-red-500 dark:text-red-400 font-semibold flex items-center gap-1 mt-1 animate-fade-in">
                    <AlertCircle size={12} />
                    Passwords do not match
                  </p>
                )}
              </div>

              {/* Toggle to switch to login */}
              <div className="flex items-center justify-center pt-2">
                <button
                  type="button"
                  disabled={isSubmitting}
                  onClick={() => {
                    setViewMode('login');
                    setError(null);
                    setSuccessMessage(null);
                  }}
                  className="text-xs font-bold text-indigo-650 dark:text-indigo-400 hover:text-indigo-850 dark:hover:text-indigo-300 hover:underline transition-colors focus:outline-none cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Already have an account? Log In
                </button>
              </div>

              {/* Consent Checkbox */}
              <div className="flex items-start gap-2.5 py-1 text-left select-none">
                <input
                  id="signup-consent-checkbox"
                  type="checkbox"
                  disabled={isSubmitting}
                  checked={signUpHasAgreedToTerms}
                  onChange={(e) => setSignUpHasAgreedToTerms(e.target.checked)}
                  className="mt-0.5 w-4 h-4 text-indigo-650 border-slate-300 rounded focus:ring-indigo-500 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed shrink-0"
                />
                <label 
                  htmlFor="signup-consent-checkbox" 
                  className="text-xs font-semibold text-slate-650 dark:text-slate-350 leading-snug cursor-pointer"
                >
                  I agree to the{' '}
                  <button
                    type="button"
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      setIsTermsOpen(true);
                    }}
                    className="text-indigo-650 dark:text-indigo-400 font-bold hover:underline hover:text-indigo-850 dark:hover:text-indigo-300 cursor-pointer transition-colors"
                  >
                    Terms of Service
                  </button>{' '}
                  and{' '}
                  <button
                    type="button"
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      setIsPrivacyOpen(true);
                    }}
                    className="text-indigo-650 dark:text-indigo-400 font-bold hover:underline hover:text-indigo-850 dark:hover:text-indigo-300 cursor-pointer transition-colors"
                  >
                    Privacy Policy
                  </button>
                </label>
              </div>

              {/* Submit Action */}
              <button
                type="submit"
                disabled={!isSignUpValid || isSubmitting}
                className="w-full flex items-center justify-center gap-2 bg-indigo-650 hover:bg-indigo-700 text-white font-bold text-sm py-3 px-4 rounded-lg shadow-md hover:shadow-lg disabled:opacity-55 disabled:cursor-not-allowed cursor-pointer transition select-none mt-2 shrink-0 h-[44px]"
              >
                {isSubmitting ? (
                  <>
                    <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    <span>Creating Account...</span>
                  </>
                ) : (
                  'Create Account'
                )}
              </button>
            </form>
          )
        )}

        {viewMode === 'recovery' && (
          <div className="space-y-4 animate-fade-in">
            {/* Tab switcher inside the recovery panel */}
            <div className="flex border-b border-slate-200 dark:border-slate-850 mb-5">
              <button
                type="button"
                disabled={loading}
                onClick={() => {
                  setRecoveryMode('password');
                  setError(null);
                  setSuccessMessage(null);
                  setFoundUsername(null);
                  setNotFoundStatus(false);
                }}
                className={`flex-1 text-center pb-2.5 text-xs font-bold uppercase tracking-wider border-b-2 transition cursor-pointer ${
                  recoveryMode === 'password'
                    ? 'border-indigo-600 text-indigo-650 dark:border-indigo-400 dark:text-indigo-400'
                    : 'border-transparent text-slate-400 hover:text-slate-600 dark:hover:text-slate-300'
                }`}
              >
                Forgot Password
              </button>
              <button
                type="button"
                disabled={loading}
                onClick={() => {
                  setRecoveryMode('username');
                  setError(null);
                  setSuccessMessage(null);
                  setFoundUsername(null);
                  setNotFoundStatus(false);
                }}
                className={`flex-1 text-center pb-2.5 text-xs font-bold uppercase tracking-wider border-b-2 transition cursor-pointer ${
                  recoveryMode === 'username'
                    ? 'border-indigo-600 text-indigo-650 dark:border-indigo-400 dark:text-indigo-400'
                    : 'border-transparent text-slate-400 hover:text-slate-600 dark:hover:text-slate-300'
                }`}
              >
                Forgot Username
              </button>
            </div>

            {/* Form state/response card rendering */}
            {successMessage ? (
              /* Success card for Forgot Password flow */
              <div className="space-y-6 text-center animate-fade-in py-2">
                <div className="inline-flex p-3 bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 rounded-full">
                  <CheckCircle size={32} className="animate-bounce" />
                </div>
                <div className="space-y-2">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                    Instructions Sent
                  </h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-semibold px-4">
                    {successMessage}
                  </p>
                </div>
                
                <div className="flex flex-col gap-2 pt-2">
                  <button
                    type="button"
                    onClick={() => {
                      setOtpEmail(recoveryEmail || email || '');
                      setOtpToken('');
                      setViewMode('otp');
                      setError(null);
                      setSuccessMessage(null);
                    }}
                    className="w-full flex items-center justify-center gap-1.5 bg-indigo-650 hover:bg-indigo-700 text-white font-bold text-sm py-2.5 px-4 rounded-lg shadow-md hover:shadow-lg transition cursor-pointer"
                  >
                    <span>Enter Code Manually</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setViewMode('login');
                      setError(null);
                      setSuccessMessage(null);
                    }}
                    className="w-full flex items-center justify-center gap-2 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-sm py-2.5 px-4 rounded-lg transition cursor-pointer"
                  >
                    <ArrowLeft size={16} />
                    <span>Back to Login</span>
                  </button>
                </div>
              </div>
            ) : foundUsername ? (
              /* Success card for Found Username in Forgot Username flow */
              <div className="space-y-6 text-center animate-fade-in py-2">
                <div className="inline-flex p-3 bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400 rounded-full">
                  <CheckCircle size={32} className="text-indigo-600 dark:text-indigo-400" />
                </div>
                <div className="space-y-3 px-4">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                    Username Found
                  </h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                    We located the following username registered to your email:
                  </p>
                  
                  {/* Display & Copy block */}
                  <div className="flex items-center justify-between gap-2.5 bg-slate-50 dark:bg-slate-950 p-3 rounded-lg border border-slate-200 dark:border-slate-800 font-mono text-sm font-semibold select-all text-slate-800 dark:text-slate-200">
                    <span className="truncate">{foundUsername}</span>
                    <button
                      type="button"
                      onClick={handleCopyUsername}
                      className="text-indigo-600 hover:text-indigo-800 dark:text-indigo-400 dark:hover:text-indigo-300 p-1 rounded-md hover:bg-slate-100 dark:hover:bg-slate-900 transition shrink-0"
                      title="Copy username to clipboard"
                    >
                      {copySuccess ? (
                        <span className="text-[10px] font-bold text-emerald-600 dark:text-emerald-400 font-sans uppercase">Copied!</span>
                      ) : (
                        <Copy size={16} />
                      )}
                    </button>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => {
                    setViewMode('login');
                    setError(null);
                    setFoundUsername(null);
                  }}
                  className="w-full flex items-center justify-center gap-2 bg-indigo-650 hover:bg-indigo-700 text-white font-bold text-sm py-2.5 px-4 rounded-lg shadow-md hover:shadow-lg transition cursor-pointer"
                >
                  <ArrowLeft size={16} />
                  <span>Proceed to Login</span>
                </button>
              </div>
            ) : notFoundStatus ? (
              /* Safe/Generic 'Not Found' notification card to avoid security issues */
              <div className="space-y-6 text-center animate-fade-in py-2">
                <div className="inline-flex p-3 bg-amber-50 dark:bg-amber-950/40 text-amber-600 dark:text-amber-400 rounded-full">
                  <AlertCircle size={32} />
                </div>
                <div className="space-y-2">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                    Search Process Completed
                  </h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-semibold px-4">
                    For security purposes, if an active account is matched with <span className="font-bold text-slate-700 dark:text-slate-350">{recoveryEmail}</span>, the corresponding details have been prepared or dispatched.
                  </p>
                  <p className="text-[11px] text-slate-400 dark:text-slate-500 italic px-4">
                    Please make sure your spelling is correct and try again if necessary.
                  </p>
                </div>
                <div className="flex flex-col gap-2.5">
                  <button
                    type="button"
                    onClick={() => {
                      setNotFoundStatus(false);
                      setRecoveryEmail('');
                    }}
                    className="w-full flex items-center justify-center gap-1.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-xs py-2.5 px-4 rounded-lg transition cursor-pointer"
                  >
                    Try Another Email
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setViewMode('login');
                      setNotFoundStatus(false);
                      setRecoveryEmail('');
                    }}
                    className="w-full flex items-center justify-center gap-1.5 text-xs font-bold text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 cursor-pointer py-2 transition hover:underline"
                  >
                    <ArrowLeft size={14} />
                    <span>Back to Login</span>
                  </button>
                </div>
              </div>
            ) : (
              /* Dynamic single-email recovery form layout */
              <form onSubmit={handleRecoverySubmit} className="space-y-4 animate-fade-in">
                {error && (
                  <div className="flex gap-2.5 items-start p-3.5 bg-red-50 dark:bg-red-950/20 text-red-700 dark:text-red-400 border border-red-200 dark:border-red-900/30 rounded-lg text-xs font-semibold leading-relaxed">
                    <AlertCircle size={16} className="shrink-0 mt-0.5" />
                    <span>{error}</span>
                  </div>
                )}

                {/* Unified helper descriptive text */}
                <div className="p-3 bg-slate-50 dark:bg-slate-950 rounded-lg text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-medium border border-slate-150 dark:border-slate-850">
                  {recoveryMode === 'password' ? (
                    'Enter the email address registered with your account, and we will send you a secure link to reset your password credentials.'
                  ) : (
                    'Enter the email address associated with your account to securely search the registered profile record.'
                  )}
                </div>

                {/* Email input (labeled dynamically to correspond cleanly) */}
                <div className="space-y-1">
                  <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                    {recoveryMode === 'password' ? 'Account Email Address' : 'Search Email Address'}
                  </label>
                  <div className="relative">
                    <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                      <Mail size={16} />
                    </span>
                    <input
                      type="email"
                      required
                      value={recoveryEmail}
                      onChange={(e) => setRecoveryEmail(e.target.value)}
                      placeholder="you@example.com"
                      className="w-full bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm border border-slate-200 dark:border-slate-800 rounded-lg pl-10 pr-4 py-2.5 outline-none focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900 transition font-medium"
                    />
                  </div>
                </div>

                {/* Submit / Navigation triggers */}
                <div className="flex flex-col gap-2.5 pt-2">
                  <button
                    type="submit"
                    disabled={loading}
                    className="w-full flex items-center justify-center gap-2 bg-indigo-650 hover:bg-indigo-700 text-white font-bold text-sm py-3 px-4 rounded-lg shadow-md hover:shadow-lg disabled:opacity-55 disabled:cursor-not-allowed cursor-pointer transition select-none h-[44px]"
                  >
                    {loading ? (
                      <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    ) : recoveryMode === 'password' ? (
                      'Send Reset Link'
                    ) : (
                      'Lookup Username'
                    )}
                  </button>

                  {/* Fallback code trigger inside recovery password panel */}
                  {recoveryMode === 'password' && (
                    <button
                      type="button"
                      onClick={() => {
                        setOtpEmail(recoveryEmail || email || '');
                        setOtpToken('');
                        setViewMode('otp');
                        setError(null);
                        setSuccessMessage(null);
                      }}
                      className="text-xs font-bold text-indigo-650 dark:text-indigo-400 hover:text-indigo-850 dark:hover:text-indigo-300 hover:underline transition-colors py-1 cursor-pointer focus:outline-none"
                    >
                      Have a recovery code instead?
                    </button>
                  )}

                  <button
                    type="button"
                    onClick={() => {
                      setViewMode('login');
                      setError(null);
                      setSuccessMessage(null);
                      setFoundUsername(null);
                      setNotFoundStatus(false);
                    }}
                    disabled={loading}
                    className="w-full flex items-center justify-center gap-1.5 text-xs font-bold text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 cursor-pointer py-2 transition hover:underline"
                  >
                    <ArrowLeft size={14} />
                    <span>Back to Login</span>
                  </button>
                </div>
              </form>
            )}
          </div>
        )}

        {viewMode === 'otp' && (
          <form onSubmit={handleVerifyOtpSubmit} className="space-y-4 animate-fade-in">
            {error && (
              <div className="flex gap-2.5 items-start p-3.5 bg-red-50 dark:bg-red-950/20 text-red-700 dark:text-red-400 border border-red-200 dark:border-red-900/30 rounded-lg text-xs font-semibold leading-relaxed">
                <AlertCircle size={16} className="shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}

            {/* Helper message */}
            <div className="p-3 bg-slate-50 dark:bg-slate-950 rounded-lg text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-medium border border-slate-150 dark:border-slate-850">
              Please check your email inbox for a 6-digit verification code. Enter your email address and the code below to securely verify your identity.
            </div>

            {/* Email Input */}
            <div className="space-y-1">
              <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                Email Address
              </label>
              <div className="relative">
                <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                  <Mail size={16} />
                </span>
                <input
                  type="email"
                  required
                  value={otpEmail}
                  onChange={(e) => setOtpEmail(e.target.value)}
                  placeholder="you@example.com"
                  className="w-full bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm border border-slate-200 dark:border-slate-800 rounded-lg pl-10 pr-4 py-2.5 outline-none focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900 transition font-medium"
                />
              </div>
            </div>

            {/* Code Input */}
            <div className="space-y-1">
              <label className="block text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider font-mono">
                6-Digit Recovery Code
              </label>
              <div className="relative">
                <span className="absolute inset-y-0 left-3 flex items-center text-slate-400 pointer-events-none">
                  <Lock size={16} />
                </span>
                <input
                  type="text"
                  required
                  autoFocus
                  maxLength={10}
                  value={otpToken}
                  onChange={(e) => {
                    const val = e.target.value.replace(/\s+/g, '');
                    setOtpToken(val);
                  }}
                  placeholder="123456"
                  className="w-full bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm border border-slate-200 dark:border-slate-800 rounded-lg pl-10 pr-4 py-2.5 outline-none focus:border-indigo-500 dark:focus:border-indigo-400 focus:bg-white dark:focus:bg-slate-900 transition font-medium tracking-widest text-center"
                />
              </div>
            </div>

            {/* Submit / Back triggers */}
            <div className="flex flex-col gap-2.5 pt-2">
              <button
                type="submit"
                disabled={loading}
                className="w-full flex items-center justify-center gap-2 bg-indigo-650 hover:bg-indigo-700 text-white font-bold text-sm py-3 px-4 rounded-lg shadow-md hover:shadow-lg disabled:opacity-55 disabled:cursor-not-allowed cursor-pointer transition select-none h-[44px]"
              >
                {loading ? (
                  <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  'Verify Code'
                )}
              </button>

              <button
                type="button"
                onClick={() => {
                  setViewMode('recovery');
                  setError(null);
                  setSuccessMessage(null);
                }}
                disabled={loading}
                className="w-full flex items-center justify-center gap-1.5 text-xs font-bold text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 cursor-pointer py-2 transition hover:underline animate-fade-in"
              >
                <ArrowLeft size={14} />
                <span>Back to Recovery Options</span>
              </button>
            </div>
          </form>
        )}
      </div>

      {/* Terms of Service Modal */}
      {isTermsOpen && (
        <div className="fixed inset-0 z-[150] flex items-center justify-center p-4">
          <div 
            className="absolute inset-0 bg-slate-950/75 backdrop-blur-xs transition-opacity duration-300"
            onClick={() => setIsTermsOpen(false)}
          />
          <div className="relative bg-white dark:bg-slate-900 w-full max-w-lg rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-800 p-6 flex flex-col max-h-[80vh] text-slate-900 dark:text-white z-[160] animate-fade-in">
            {/* Header */}
            <div className="flex items-center justify-between border-b border-slate-150 dark:border-slate-800 pb-3 mb-4">
              <h3 className="text-sm font-black uppercase tracking-wider font-mono text-indigo-650 dark:text-indigo-400">
                Terms of Service
              </h3>
              <button
                type="button"
                onClick={() => setIsTermsOpen(false)}
                className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
              >
                <X size={18} />
              </button>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 overflow-y-auto pr-2 space-y-4 text-xs text-slate-600 dark:text-slate-350 leading-relaxed font-semibold whitespace-pre-wrap text-left">
              {TOS_PLACEHOLDER_TEXT}
            </div>

            {/* Footer */}
            <div className="flex items-center justify-end gap-3 pt-4 mt-4 border-t border-slate-100 dark:border-slate-800">
              <button
                type="button"
                onClick={() => setIsTermsOpen(false)}
                className="px-4 py-2 bg-indigo-650 hover:bg-indigo-700 text-white rounded-lg text-xs font-bold transition cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Privacy Policy Modal */}
      {isPrivacyOpen && (
        <div className="fixed inset-0 z-[150] flex items-center justify-center p-4">
          <div 
            className="absolute inset-0 bg-slate-950/75 backdrop-blur-xs transition-opacity duration-300"
            onClick={() => setIsPrivacyOpen(false)}
          />
          <div className="relative bg-white dark:bg-slate-900 w-full max-w-lg rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-800 p-6 flex flex-col max-h-[80vh] text-slate-900 dark:text-white z-[160] animate-fade-in">
            {/* Header */}
            <div className="flex items-center justify-between border-b border-slate-150 dark:border-slate-800 pb-3 mb-4">
              <h3 className="text-sm font-black uppercase tracking-wider font-mono text-indigo-650 dark:text-indigo-400">
                Privacy Policy
              </h3>
              <button
                type="button"
                onClick={() => setIsPrivacyOpen(false)}
                className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
              >
                <X size={18} />
              </button>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 overflow-y-auto pr-2 space-y-4 text-xs text-slate-600 dark:text-slate-350 leading-relaxed font-semibold whitespace-pre-wrap text-left">
              {PRIVACY_PLACEHOLDER_TEXT}
            </div>

            {/* Footer */}
            <div className="flex items-center justify-end gap-3 pt-4 mt-4 border-t border-slate-100 dark:border-slate-800">
              <button
                type="button"
                onClick={() => setIsPrivacyOpen(false)}
                className="px-4 py-2 bg-indigo-650 hover:bg-indigo-700 text-white rounded-lg text-xs font-bold transition cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
